### ISSUE TITLE
Unify the name of the app

### ISSUE THREAD

**Issue by ryonakano** [elementary/capnet-assist#44]
The name of the app does not seem to be unified.

In the appdata and desktop file, it is written as "Captive Network Assistant":

https://github.com/elementary/capnet-assist/blob/e37b52c21f3671c6f7b50293b9f0b90799752687/data/io.elementary.capnet-assist.desktop.in#L2

https://github.com/elementary/capnet-assist/blob/e37b52c21f3671c6f7b50293b9f0b90799752687/data/io.elementary.capnet-assist.appdata.xml.in#L8

However, in the codes of this repo, the README.md and [in the Open Source page of the website](https://elementary.io/open-source) it is written as "Captive Portal Assistant."

The name is not unified and this might make users confusing. I think we should unify the name of the app to either notation.

**Comment by cassidyjames** [comment]
It looks like the only remaining mentions of "portal" are when it's talking about loading the captive portal itself, so this should be fixed by the two linked issues.
