### ISSUE TITLE
Window stays on foreground

### ISSUE THREAD

**Issue by simjnd** [elementary/capnet-assist#74]
### What Happened?

The window showing the login page to the captive network stays on the foreground, I can't dock it or place other windows in front of it.

### Steps to Reproduce

1. Connect to a captive network
2. Wait for the captive network assistant window to pop-up
3. Try to bring other apps in the foreground

### Expected Behavior

The window should be able to be moved to the background : I store the passwords to the captive networks I have to use in my password manager, but I can't use my password manager because the captive network assistant window takes up the whole space of my 13' Lo-DPI screen. It forces me to lookup the password on another device and have to type it manually which is very inconvenient.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by tooxo** [comment]
If you are able to see the top bar of the window you can right-click it and disable "Always on Top".

**Comment by danirabbit** [comment]
Fixed in #112
