### ISSUE TITLE
support for webkit2gtk-4.1

### ISSUE THREAD

**Issue by decathorpe** [elementary/capnet-assist#84]
Starting with GNOME 43, some core components of the desktop have been ported to libsoup-3, which apparently brings a lot of new features, including HTTP/2 support. However, applications and libraries **cannot** load both libsoup-2.4 and libsoup-3 in the same process, as this is unsupported and will crash the application immediately.

The elementary Captive Portal Assistant will also be affected this change eventually, but at least not immediately. It links against webkit2gtk-4.0, which is only compatible with libsoup-2.4, but since it will remain available, at least this project will continue to build and work on GNOME 43. However, webkit2gtk-4.0 will be removed by upstream GNOME in the near-to-mid-future, so capnet-assist needs to support webkit2gtk-4.1 sooner rather than later.

Additionally, if one of the other GNOME libraries that's linked to by capnet-assist gets ported from libsoup-2.4 to libsoup-3, it will also be in trouble even earlier than the webkit2gtk-4.0 removal date, as building against a library that only supports libsoup-3 **and** webkit2gtk-4.0 will either not work or result in non-functional application binaries.

**Comment by bobby285271** [comment]
This is resolved in https://github.com/elementary/capnet-assist/commit/265599873308af6a1f0c8fcc21a5331b9a66a4ed :laughing:
