### ISSUE TITLE
support for gcr-4

### ISSUE THREAD

**Issue by decathorpe** [elementary/capnet-assist#85]
GNOME 43 will be released with a new major version of gcr (gcr-4 vs. gcr-3).

At least in Fedora 37, those two will be packaged separately and installable in parallel, but gcr-3 will not be supported forever. capnet-assist will, at some point, need to add support for, or be ported to, gcr-4.

More context for this change is available on the [Fedora development mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/YODKNTAEVT4I7YKXSZ2TYVNAZLUGDXJF/).

**Comment by davidmhewitt** [comment]
We'd actually need to provide our own widget here because Gcr no longer ships UI widgets in gcr-4, which is the only thing we use it for here:

https://gitlab.gnome.org/GNOME/gcr/-/blob/master/NEWS#L6

**Comment by danirabbit** [comment]
Fixed in #113 :)
