### ISSUE TITLE
Low contrast background in AppCenter

### ISSUE THREAD

**Issue by lenemter** [elementary/capnet-assist#92]
### What Happened?

![image](https://user-images.githubusercontent.com/80143868/206892310-93bb2582-ff24-4f19-8368-f7ef647e667d.png)
![image](https://user-images.githubusercontent.com/80143868/206892323-dd8e36df-0a41-4358-aa0a-f7f8662e34ef.png)

### Steps to Reproduce

1. Open AppCenter
2. Open Capnet Assistant page

### Expected Behavior

Not white text on white background

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Fixed in #102
